<a href="https://colab.research.google.com/github/KedalaSahithya/AIML/blob/main/Lab_Gen_Ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Step 1: Define the actual and predicted values
y_actual = [20, 30, 40, 50]  # Given actual values
y_pred = [20.5, 30.3, 40.2, 50.6]  # Given predicted values

# Step 2: Compute MSE manually
n = len(y_actual)  # Number of data points
mse_manual = sum((y_actual[i] - y_pred[i])**2 for i in range(n)) / n  # MSE formula

# Step 3: Compute MSE using sklearn for verification
from sklearn.metrics import mean_squared_error
mse_library = mean_squared_error(y_actual, y_pred)

# Step 4: Print both results
print(f"MSE computed manually: {mse_manual}")
print(f"MSE computed using sklearn: {mse_library}")


MSE computed manually: 0.18500000000000083
MSE computed using sklearn: 0.18500000000000083


In [ ]:
# Step 1: Define the actual and predicted values
y_actual = [20, 30, 40, 50]  # Given actual values
y_pred = [20.5, 30.3, 40.2, 50.6]  # Given predicted values

# Step 2: Compute MAE manually
n = len(y_actual)  # Number of data points
mae_manual = sum(abs(y_actual[i] - y_pred[i]) for i in range(n)) / n  # MAE formula

# Step 3: Compute MAE using sklearn for verification
from sklearn.metrics import mean_absolute_error
mae_library = mean_absolute_error(y_actual, y_pred)

# Step 4: Print both results
print(f"MAE computed manually: {mae_manual}")
print(f"MAE computed using sklearn: {mae_library}")


MAE computed manually: 0.40000000000000124
MAE computed using sklearn: 0.40000000000000124


In [ ]:
# Step 1: Define the actual and predicted values
y_actual = [20, 30, 40, 50]  # Given actual values
y_pred = [20.5, 30.3, 40.2, 50.6]  # Given predicted values

# Step 2: Compute RMSE manually
n = len(y_actual)  # Number of data points
mse_manual = sum((y_actual[i] - y_pred[i])**2 for i in range(n)) / n  # MSE formula
rmse_manual = mse_manual ** 0.5  # Taking square root to get RMSE

# Step 3: Compute RMSE using sklearn for verification
from sklearn.metrics import mean_squared_error
# Calculate MSE first
mse_library = mean_squared_error(y_actual, y_pred)
# Then calculate RMSE by taking the square root of MSE
rmse_library = mse_library ** 0.5  # Calculate RMSE from MSE

# Step 4: Print both results
print(f"RMSE computed manually: {rmse_manual}")
print(f"RMSE computed using sklearn: {rmse_library}")

RMSE computed manually: 0.4301162633521323
RMSE computed using sklearn: 0.4301162633521323


In [ ]:
# Step 1: Import Necessary Libraries
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

# Step 2: Define Actual and Predicted Values
y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred =   [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]

# Step 3: Compute Confusion Matrix and Accuracy
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)

# Step 4: Display Results
print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}")


Confusion Matrix:
 [[2 1 2]
 [2 1 2]
 [2 1 2]]
Accuracy: 0.3333
